### PR TITLE
Workout history update

### PR DESCRIPTION
**Pull request by robDevs**
# Info
This PR attaches a listener to the Workout History calendar. When the selected date it changed it should fetch the most recent workout for the selected date and display it below the calendar. 

# Testing. 
You must have workouts in the database for it to fetch any. Navigate to the Workout History page and select a date.

### CODE REVIEW

**Review by Shiviandemon — APPROVED** [review]
Works as intended for me! Fantastic changes. 
(only 2 commits? Come on... you're supposed to milk it for the crown) xD
Even did the Last Workout Highlights for the calendar too!
Still needs more information about the last workout added and a limiter to only show the workout of the day you clicked on, but this can be done later.

Button still needs removed as far as I can tell, but otherwise a perfect addition.
WorkoutHistory_PullRequest

**Review by wickhamkl007 — APPROVED** [review]
This all looks awesome Rob I see no issues! Other than what Tim said that button needs to be removed

**Review by lastbestdev — COMMENTED** [review]
First and foremost - this is absolutely sick. It works!!!

BUT 🐛  there appears to be some issues with the ACTUAL tracked workouts. We seem to be storing the wrong DateCompleted on the actual tracked workouts. Here's a screenshot showing that (the top 3 are actual tracked workouts, the rest are from your `setRandomWorkouts` method)

image

This results in the actual tracked workouts not showing up in the workout history... at least I'm pretty sure.

**Review by lastbestdev — APPROVED** [review]
Patched. Ship it!!! 💪 🤓  WE DID IT!

# New test plan:
* Prerequisite: clear out your db
* Confirm the latest workout highlights on the home page is from the 15th
* Navigate to the WorkoutHistory and select the 15th. The same highlights should show.
* Track a workout. Once you're done, confirm that the highlights on the home page has updated to today's date, and the workout you tracked
* Navigate to the calendar in the WorkoutHistory and check today's date for the same info.

**Review by jacobbexten — APPROVED** [review]
I believe the date is off by one. It's giving me data for tomorrow the 24th. Other than that, it's beautiful.

**Pull request merged**
