### PR TITLE
Revert "Edit README.md"

### PR DESCRIPTION
**Pull request by lastbestdev**
Looks like we had someone accidentally merge the test-branch in to our code (master) - whoops! 

No worries, this is exactly what git is for. Rolling back to old master branch.

Reverts braddeibert/musclenerds#1

### CODE REVIEW

**Review by robDevs — CHANGES_REQUESTED** [review]
There is a couple of ways this can be fixed (that I can think of). The first would be manually changing git history (I would never actually recommend this). 

The other method would be to simply revert the changes in a new commit and submit a new PR.

**Comment by robDevs** [comment]
I think I misread the changes in my original comment for this. It looks like this PR is actually reverting the changes from the last PR that was not meant to be merged. Looks good to me.

**Comment by lastbestdev** [comment]
@robDevs can I get an approval then? damn 😆

**Review by JosiahHamer2 — APPROVED** [review]

**Review by Shiviandemon — APPROVED** [review]

**Review by jacobbexten — APPROVED** [review]

**Review by jseeley452 — APPROVED** [review]

**Comment by lastbestdev** [comment]
Whoops! Looks like someone accidentally closed the PR. 

A rule of thumb going forward, you should almost never merge or close someone else's pull request (PR). The person who opened the PR should be responsible for merging/closing/deleting when they are ready.

**Review by robDevs — APPROVED** [review]

**Review by Joshewah11 — APPROVED** [review]

**Pull request merged**
