### PR TITLE
Exercise view branch

### PR DESCRIPTION
**Pull request by JosiahHamer2**
ADDED:
- Hooked up Exercise Library to the database.
- Made imagebuttons in exercise library switch fragments to IndividualExercise Fragment
- Populated Individual excercise fragment with database values

TESTING:
- Each database item should appear on the recyclerview in exercise_view
- Each exercise item should appear on individualexercise fragment
- Each image button in exercise library should bring up a unique fragment for that exercise

Still need to add separate images for each exercise in exercise library, and also need to get images to appear at the bottom of 
the individual exercise fragments, but once that's done the exerciseview stuff should be done. 

Also if each exercise view is going to have a different video, that will need to be set in the database at some point, and if each exercise had a link to the url of an image in its database they could all have different images in the recyclerview, otherwise  just having basic arbitrary images is probably good enough.

### CODE REVIEW

**Review by wickhamkl007 — APPROVED** [review]
All of this looks great Josiah! I didn't run into any issues nor did I see anything out of place. Great work!

**Review by robDevs — CHANGES_REQUESTED** [review]
`exerciseNameText.setText(exerciseName);
        muscleGroupsText.setText(selectedExercise.getTarget_muscles());
        setsText.setText(String.valueOf(selectedExercise.getSets()));
        repsText.setText(String.valueOf(selectedExercise.getReps()));
        equipmentText.setText(selectedExercise.getEquipment());
        etcText.setText(selectedExercise.getDescription());`
        
These type of front end changes need to be sent to a separate thread that is dedicated for ui changes. See general chat in our discord for an example.

**Review by Shiviandemon — APPROVED** [review]
Works as of 4/14/21 4pm

**Review by jacobbexten — APPROVED** [review]
Looking great so far. This is a great start!

**Comment by lastbestdev** [comment]
Working on some changes to fix design of individual exercise view (`exercise_fragment.xml`). Currently appears like so: 

image

**Comment by robDevs** [comment]
Files in the model folder should only be files that represent database tables. Please move / rename the files that this adds to the model folder. 

I am also in the process of making database tables for MuscleGroups that will effect how you are getting data about the muscle groups. It may be best to hold off on this PR until these database changes are implemented.

**Pull request merged**
